### PR TITLE
PR: Refactor for API/Function signature inconsistency #24 🤦‍♂️ 

### PR DESCRIPTION
**Pull request by nelsonic**
See: #24

### CODE REVIEW

**Comment by nelsonic** [comment]
I've kinda broken the `Gogs.local_branch_create/2` function ... so need to fix it first. 
But it's one of the functions we want to refactor to require the `org_name`. 
Hopefully, this won't be too painful. 🤞

**Comment by nelsonic** [comment]
With the work you did on #28 merged into this PR, I think we could totally merge it now. 🤞 
Lemme just fix the failing test and will assign to you for review. ⏳

**Comment by nelsonic** [comment]
Sadly, one of the tests is still failing: 

image

https://github.com/dwyl/gogs/runs/6391663397?check_suite_focus=true#step:8:117
image

Tempted to just re-write this to make it pass!

**Comment by nelsonic** [comment]
@SimonLab I've reviewed your additions and they look great!
Sadly I cannot _approve_ the PR because I _opened_ it ...

image

Please review/merge when you can tomorrow. Thanks.

**Review by SimonLab — APPROVED** [review]
:+1: thanks for looking at the tests

**Comment by nelsonic** [comment]
Merci @SimonLab 🙌☀️

**Pull request merged**
